# Config file for Fastlane - tool to build apps, run tests, and more. 

# Ideally, we can reuse the config files from the native SDKs. To do that, import thier Fastlanes which means we can call the functions inside of them. 
# See the Fastfiles for those projects to learn more about how to use them. 

import_from_git(
  url: "https://github.com/customerio/customerio-ios.git", 
  branch: "levi/ci/make-fastlane-reusable", 
  path: "Apps/fastlane/Fastfile"
)

# the iOS SDK Fastlane imports functions for code signing iOS. 
# See this README (https://github.com/customerio/apple-code-signing) for list of all fastlane functions that this imports and you can run. 