# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane'
gem 'cocoapods'
gem 'fastlane-plugin-firebase_app_distribution'
gem 'fastlane-plugin-versioning_android'
gem 'fastlane-plugin-find_firebase_app_id'