require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'SampleApp' do
  config = use_native_modules!
#use_frameworks!
  # Flags change depending on the env values.
  flags = get_default_flags()
  use_frameworks!
    use_modular_headers!
    pod 'FirebaseMessaging'
  pod 'CustomerIO/MessagingPushFCM', '2.1.2'

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
  )
end

target 'Notification Service' do
  use_frameworks!
  pod 'CustomerIO/MessagingPushFCM', '2.1.2'
end
post_install do |installer|
    react_native_post_install(installer)
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
          end
      end
  end
