# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  Pod::UI.puts "Configuring Pod with use_frameworks! default".green
  use_frameworks!
end

abstract_target 'CustomerIO_RN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'CustomerIODataPipelines', :path => '../../cio-native-sdks/customerio-ios'
  pod 'CustomerIOMessagingInApp', :path => '../../cio-native-sdks/customerio-ios'
  
  target 'APN' do
    pod 'CustomerIOReactNativePush/APN', :path => '../..'
    pod 'CustomerIOMessagingPushAPN', :path => '../../cio-native-sdks/customerio-ios'
    
  end

  target 'FCM' do
    pod 'CustomerIOReactNativePush/FCM', :path => '../..'
    pod 'CustomerIOMessagingPushFCM', :path => '../../cio-native-sdks/customerio-ios'
  end
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end

target 'APN_NSE' do
  pod 'CustomerIOMessagingPushAPN', :path => '../../cio-native-sdks/customerio-ios'
end

target 'FCM_NSE' do
  pod 'CustomerIOMessagingPushFCM', :path => '../../cio-native-sdks/customerio-ios'
end
