export const BORDER_RADIUS_DEFAULT = 4;

export const BACK_BUTTON_MARGIN_LEFT = 0;
export const BACK_BUTTON_MARGIN_RIGHT = 32;
export const BUTTON_BORDER_RADIUS = BORDER_RADIUS_DEFAULT;
export const BUTTON_MAX_WIDTH = 320;
export const BUTTON_PADDING_HORIZONTAL = 20;
export const BUTTON_PADDING_VERTICAL = 12;
export const IMAGE_BUTTON_PADDING = 16;
export const IMAGE_BUTTON_ICON_SIZE = 24;
export const INPUT_FIELD_BORDER_RADIUS = BORDER_RADIUS_DEFAULT;
export const INPUT_FIELD_BORDER_WIDTH_BOTTOM = 1;
export const INPUT_FIELD_HEIGHT = 40;
export const INPUT_FIELD_MAX_WIDTH = 488;
export const INPUT_FIELD_PADDING_HORIZONTAL = 4;
export const TOP_BAR_HEIGHT = 72;
export const TOP_BAR_PADDING_HORIZONTAL = 16;
