# Re-use iOS SDK Fastfile. It's highly suggested to only have this import function in this file and all modifications are done to iOS SDK's Fastfile
import_from_git(
  url: "https://github.com/customerio/customerio-ios.git",
  branch: "main", # The branch to checkout on the repository.
  path: "Apps/fastlane/Fastfile" # The path of the Fastfile in the repository.
)