#require_relative '../node_modules/react-native/scripts/react_native_pods'
#require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#
#platform :ios, '13.0'
#
#target 'SampleApp' do
#  use_unimodules!
#  config = use_native_modules!
#
#  use_react_native!(:path => config["reactNativePath"])
#  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
#  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'
#  pod 'CustomerIO/MessagingPushAPN', '~> 1.2.5'
#  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
#
#  # Uncomment to opt-in to using Flipper
#  #
#  # if !ENV['CI']
#  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
#  #   post_install do |installer|
#  #     flipper_post_install(installer)
#  #   end
#  # end
#end
#
#target 'Notification Service' do
#  pod 'CustomerIO/MessagingPushAPN', '~> 1.2.5'
#end
#
## workaround for xcode14 for a react native dependency: https://github.com/expo/eas-cli/issues/1432#issuecomment-1285199900
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
#      target.build_configurations.each do |config|
#          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#      end
#    end
#  end
#end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'SampleApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'CustomerIO/MessagingPushAPN', '2.1.2'

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'Notification Service' do
  pod 'CustomerIO/MessagingPushAPN', '2.1.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
