name: Build sample apps

on:
  pull_request: # build sample apps for every commit pushed to an open pull request (including drafts)
  push:
    branches: [ main, feature/* ]

concurrency: # cancel previous workflow run if one exists.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  XCODE_VERSION: "15.3"
  RUBY_VERSION: "3.0"
  NODE_VERSION: "18"

jobs:
  update-pr-comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to be able to comment on PR
    outputs:
      comment-id: ${{ steps.create-comment.outputs.comment-id }}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: existing-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: <!-- sample app builds -->

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        id: create-comment
        with:
          comment-id: ${{ steps.existing-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- sample app builds --> 
            # Sample app builds 📱

            Below you will find the list of the latest versions of the sample apps. It's recommended to always download the latest builds of the sample apps to accurately test the pull request. 

            ---
            ${{ steps.build.outputs.build-log }}
          edit-mode: replace # replace the existing comment with new content since we are creating new builds

  build-sample-apps:
    if: ${{ always() }} # do not skip running this step if update-pr-comment does not run
    needs: [update-pr-comment] # wait for PR comment to be created saying new builds are being made.
    permissions:
      pull-requests: write # comment on pull request with build information
    strategy:
      fail-fast: false # if one sample app fails to build, let the other sample apps continue to build and not cancel them.
      matrix: # Use a matrix allowing us to build multiple apps in parallel. Just add an entry to the matrix and it will build!
        sample-app:
          # List all sample apps you want to have compiled.
          # List item is name of directory inside of "Apps" directory for the corresponding app to compile.
          - "APN"
          - "FCM"
    defaults:
      run:
        working-directory: apps/${{ matrix.sample-app }}
    runs-on: macos-14
    name: Building sample app ${{ matrix.sample-app }}

    steps:
      - uses: actions/checkout@v4

      # Install CLI tools, Ruby, and Ruby dependencies for Fastlane
      
      - name: Set Default Firebase Distribution Groups
        run: |
          # Define all the possible distribution groups
          ALL_BUILDS_GROUP="all-builds"
          FEATURE_BUILDS_GROUP="feature-branch"
          STABLE_BUILDS_GROUP="next"
          
          # Initialize with the default distribution group
          distribution_groups=("$ALL_BUILDS_GROUP")
          
          # Determine current app type and Git context
          is_primary_app=$([[ "${{ matrix.sample-app }}" == "APN" ]] && echo "true" || echo "false")
          current_branch="${GITHUB_REF}"
          
          # Append distribution groups based on branch and context if the app is primary
          if [[ "$is_primary_app" == "true" ]]; then
            [[ "$current_branch" == "refs/heads/feature/"* ]] && distribution_groups+=("$FEATURE_BUILDS_GROUP")
            [[ "$current_branch" == "refs/heads/main" ]] && distribution_groups+=("$STABLE_BUILDS_GROUP")
          fi
          
          # Export the groups as an environment variable
          echo "firebase_distribution_groups=$(IFS=','; echo "${distribution_groups[*]}")" >> $GITHUB_ENV

      - name: Install CLI tools used in CI script
        shell: bash
        run: |
          brew install sd # used in CI script as an easier to use sed CLI. Replaces text in files. 
          brew install xcbeautify # used by fastlane for output

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true # cache tools to make builds faster in future
          working-directory: apps/${{ matrix.sample-app }}

      # Update version numbers and workspace credentials before building the app

      - name: Generate New Version
        uses: maierj/fastlane-action@v3.1.0
        with:
          subdirectory: Apps/${{ matrix.sample-app }}
          lane: "generate_new_version"
          options: '{"branch_name":"${{ github.ref_name }}", "pull_request_number":"${{ github.event.pull_request.number }}"}'

      - name: Update React Native SDK Version
        uses: maierj/fastlane-action@v3.1.0
        with:
          subdirectory: Apps/${{ matrix.sample-app }}
          lane: "update_react_native_sdk_version"
        env:
          SDK_VERSION_NAME: ${{ env.SDK_VERSION_NAME }}
          APP_VERSION_NAME: ${{ env.APP_VERSION_NAME }}
          APP_VERSION_CODE: ${{ env.APP_VERSION_CODE }}

      - name: Update Sample App Version
        uses: maierj/fastlane-action@v3.1.0
        with:
          subdirectory: Apps/${{ matrix.sample-app }}
          lane: "update_react_native_app_version"
        env:
          SDK_VERSION_NAME: ${{ env.SDK_VERSION_NAME }}
          APP_VERSION_NAME: ${{ env.APP_VERSION_NAME }}
          APP_VERSION_CODE: ${{ env.APP_VERSION_CODE }}

      - name: Setup workspace credentials in React Native environment files
        run: |
          # Determine the correct file extension (.js or .ts)
          if [ -f "env.sample.js" ]; then
            ENV_FILE="env.js"
            cp "env.sample.js" "$ENV_FILE"
          elif [ -f "env.sample.ts" ]; then
            ENV_FILE="env.ts"
            cp "env.sample.ts" "$ENV_FILE"
          else
            echo "No env.sample.js or env.sample.ts file found."
            exit 1
          fi
          
          # Update keys in the environment file
          sd "siteId: '.*'" "siteId: '${{ secrets[format('CUSTOMERIO_{0}_WORKSPACE_SITE_ID', matrix.sample-app)] }}'" "$ENV_FILE"
          sd "cdpApiKey: '.*'" "cdpApiKey: '${{ secrets[format('CUSTOMERIO_{0}_WORKSPACE_CDP_API_KEY', matrix.sample-app)] }}'" "$ENV_FILE"

      - name: Setup workspace credentials in iOS environment files
        working-directory: Apps/${{ matrix.sample-app }}/ios
        run: |
          cp "Env.swift.example" "Env.swift"
          sd 'siteId: String = ".*"' "siteId: String = \"${{ secrets[format('CUSTOMERIO_{0}_WORKSPACE_SITE_ID', matrix.sample-app)] }}\"" "Env.swift"
          sd 'cdpApiKey: String = ".*"' "cdpApiKey: String = \"${{ secrets[format('CUSTOMERIO_{0}_WORKSPACE_CDP_API_KEY', matrix.sample-app)] }}\"" "Env.swift"

      # Make sure to fetch dependencies only after updating version numbers and workspace credentials

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json

      - name: Cache CocoaPods downloaded dependencies for faster builds in the future
        uses: actions/cache@v4
        with:
          path: Apps/${{ matrix.sample-app }}/Pods
          key: ${{ runner.os }}-${{ matrix.sample-app }}-Pods-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.sample-app }}-Pods

      - name: Install dependencies to build SDK
        run: npm ci
        working-directory: .

      - name: Install dependencies for sample app
        run: npm run ci:install
      
      # Android setup

      - name: Setup Android environment for sample app
        uses: customerio/customerio-android/.github/actions/setup-android@main

      - name: Build and upload Android app via Fastlane
        id: android_build
        uses: maierj/fastlane-action@v3.1.0
        with:
          subdirectory: Apps/${{ matrix.sample-app }}
          lane: 'android build'
          options: '{"distribution_groups": "${{ env.firebase_distribution_groups }}"}'
        env:
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}
        continue-on-error: true # continue to build iOS app even if Android build fails

      # iOS setup

      - name: Setup iOS environment for sample app
        uses: customerio/customerio-ios/.github/actions/setup-ios@main
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build and upload iOS app via Fastlane
        id: ios_build
        uses: maierj/fastlane-action@v3.1.0
        with:
          subdirectory: Apps/${{ matrix.sample-app }}
          lane: "ios build"
          options: '{"distribution_groups": "${{ env.firebase_distribution_groups }}"}'
        env:
          GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64: ${{ secrets.GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64 }}
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}

      - name: Check build statuses and mark failure
        run: |
          if [ "${{ steps.android_build.outcome }}" != "success" ] || [ "${{ steps.ios_build.outcome }}" != "success" ]; then
            echo "One or more builds failed."
            exit 1
          fi

      # Update PR comment with build information

      - name: Update sample builds PR comment with build information
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ needs.update-pr-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          # the variables APP_VERSION_NAME, APP_VERSION_CODE are generated above in generate_new_version lane
          body: |
            * ${{ matrix.sample-app }}: `${{ env.APP_VERSION_NAME }} (${{ env.APP_VERSION_CODE }})`
          edit-mode: append # append new line to the existing PR comment to build a list of all sample app builds.

      - name: Update sample builds PR comment with build failure message
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ needs.update-pr-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            * ${{ matrix.sample-app }}: Build failed. See [CI job logs](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) to determine the issue and try re-building.
          edit-mode: append # append new line to the existing PR comment to build a list of all sample app builds.