name: Semantic PR helper 

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]

permissions: read-all # default permission for security is reading, only 

jobs:
  pr-help:
    name: Semantic PR helper 
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to push code 
      issues: write # to make comments on issues 
      pull-requests: write # to make comments on PR
    steps:
      - name: Semantic PR helper 
        uses: levibostian/action-semantic-pr@v3
        with:
          readToken: ${{ secrets.GITHUB_TOKEN }}
                    # Sets rules on the types of commits allowed on a specific branch. Example: {"beta": "fix,docs"} gives a warning on the pull request if a pull request is made into the beta branch with a type thats not fix.
          branchTypeWarning: '{"beta": "fix", "main": "fix"}'